### ISSUE TITLE
USER STORY #1 As a player, I want to see a welcome screen so that I know how to start the game.

### ISSUE THREAD

**Issue by tomMckechnie-90** [tomMckechnie-90/The-Brain-Builders#1]
As a player, I want to see a welcome screen so that I know how to start the game.

**Acceptance Criteria:**

- [x] The welcome screen should display the game title.
- [x] There should be a "Start Game" button that begins the game.
- [x] Instructions on how to play should be visible.

**Tasks:**

- [x] Design Welcome Screen: Create HTML and CSS for the welcome screen layout.
- [x] Start Game Function: Implement a JavaScript function to start the game when the button is clicked.
- [x] Display Instructions: Add a section for game instructions on the welcome screen.
