### ISSUE TITLE
User Story 2: As a player, I want to be able to flip cards so that I can see the images.

### ISSUE THREAD

**Issue by tomMckechnie-90** [tomMckechnie-90/The-Brain-Builders#5]
As a player, I want to be able to flip cards so that I can see the images.

**Acceptance Criteria:**

- [x] Clicking on a card should flip it to reveal the image.
- [x] Only two cards can be flipped at a time.

**Tasks:**

- [x] Card Structure: Create the HTML structure for the cards.
- [x] Flip Function: Write JavaScript to handle card flipping.
- [x] CSS Animations: Add CSS to animate the card flip.
